### PR TITLE
ADNI alzheimers classification with ViT s4743401

### PR DESCRIPTION
**Pull request by Georgia-Docherty**
# Classifier Based on Vision Transformer for Alzheimer's Disease Classification

## Question

For this assignment, I chose task 5 and implemented a classifier based on a Vision Transformer (ViT) model to classify Alzheimer’s Disease (AD) and Normal Cognition (NC) from brain MRI images in the ADNI dataset. The goal was to achieve a high level of accuracy in distinguishing between AD and NC cases, ultimately improving early detection methods for Alzheimer’s Disease. More specifically, I aimed to achieve an accuracy of 0.8 against the test set. I have implemented code that processes the ADNI data for a model to train on, code for training, testing and validation of the model and additionally added code in predict.py to model these results and report the accuracy of the model's ability to classify the data. A 72%/28% train-test split was used.

## Context

The project comprises the following code files and additional directories, each of which serves a specific purpose in the data processing, model training, and evaluation pipeline:

1. **README.md**: Documentation that provides an overview of the problem, explains the model architecture, lists dependencies, outlines training and evaluation procedures, and presents the final results, along with references to related work.

2. **dataset.py**: Handles data loading, preprocessing, and transformations. This script prepares the brain MRI images from the ADNI dataset for training, validation, and testing, ensuring consistency in input data format. It also includes data augmentation techniques to improve model generalization and addresses potential data leakage issues.

3. **modules.py**: Implements the core Vision Transformer (ViT) architecture, including essential components such as PatchEmbedding, Transformer Encoder blocks, and a final classifier layer. This file encapsulates the core of the model, focusing on leveraging self-attention mechanisms to capture spatial features in MRI images.

4. **train.py**: This script manages the training of the Vision Transformer (ViT) model, tracking losses and validation performance throughout the training process. It saves the trained model for later evaluation and further analysis.

5. **predict.py**: Facilitates model evaluation by loading the pre-trained model and performing classification on the test set. This script includes configurations for batch size, patch size, learning rate, and other hyperparameters. Additionally, it provides tools for visualizing performance metrics, such as confusion matrices, to assess the model's effectiveness in distinguishing between AD and NC cases.

### Folders

- **graphs**: Contains generated plots showcasing key performance metrics, including loss plots, accuracy trends, and confusion matrices.

## Additional Information

- The Vision Transformer (ViT) model is adapted to handle 2D medical imaging data effectively, with a particular focus on extracting spatial features from MRI images (without taking too much time).
- The train.py script manages the training of the ViT model, tracking training and validation losses over epochs. This script saves model checkpoints for later evaluation and includes a function to plot the loss curves.
- The predict.py script loads the pre-trained model and performs classification on the test set. It manages configurations for batch size, patch size, learning rate, and other hyperparameters. Additionally, it provides tools for visualizing performance metrics, including a confusion matrix and results table to assess the model's effectiveness in distinguishing between AD and NC cases.
PyTorch is used as the primary framework for model implementation, with supporting libraries for data handling, visualization, and evaluation, including Matplotlib and Scikit-learn for generating plots and metrics.
- The input data is sourced from the ADNI dataset.

By Georgia Docherty, 47434011

### CODE REVIEW

**Comment by shaivikaaaa** [comment]
**This is an initial inspection**

Difficulty : Hard
Task : 5

1) Recognition Problem:

- The code structure looks good
- file structure is good
- all requirements are satisfied

2) Commit Log:

- commit messages are good

3) Documentation:

Requirement:

Tittle: Done
Description of the algorithm: Done
Problem that it solves: Done
How it works in a paragraph (example any pre-processing): Done
Figure/visualisation (any input, output & results): Done
Dependencies: Done

Add result section as well - stating the accuracy you got for each part

4) Pull Request
Nothing is in here, u have to properly write a PR as well

Feedback:
- Add result section in README  - stating the accuracy you got for each part
- Write description for PR

**Comment by Georgia-Docherty** [comment]
I've added and commit the result section to README and have added a description for PR!

**Comment by shaivikaaaa** [comment]
Hi,
I would suggest you to once look at PR's done in 2023
and update yours in the same manner.

**Comment by Georgia-Docherty** [comment]
Thank you! I've updated it again after looking at some of the more detailed ones in 2023.

**Comment by aniketgupta17** [comment]
Observational Feedback

Pull Request:
Correctly created the Pull request from Topic Recognition Branch .
The pull request  includes clear description about the file structure .
**Previous feedback incorporated .**

File Organizing: Well-organized files.

Commit Log:
Commit messages are  progressive for the Recognition Problem solved using 4 files .
Commits show a logical developement .

Documentation:
Code comments and docstrings are included.
Proper GitHub markdown formatting is used, with organized headings, lists, and code blocks.
Can add about Conclusion and future improvements in the ReadMe.

**Comment by Georgia-Docherty** [comment]
I have added the conclusion and improvements!

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>Good solution to problem. </td><td></td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. ViT (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). On time submission.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-1</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by shakes76** [comment]
PLots and more info in README could be done -1

**Pull request merged**
