### PR TITLE
s47450262-Topic-recognition-3DUnet

### PR DESCRIPTION
**Pull request by Nicholas-Roughley**
Name: Nicholas Roughley
Student Number: 47450262
Overview: The pull request implements a 3D improved Unet model used to segment MRI prostate images.

Purpose: The purpose of these modifications is to create a model that reliably and effectively gives accurate dice score coeffiecients to each class.

The added files include:
modules.py
train.py
predict.py
utils.py
dataset.py
requirements.txt
README.md

### CODE REVIEW

**Comment by celinsze** [comment]
**This is an initial inspection, no action is required at this point**

Recognition problem: 
Problem Solving: 
•	Segmentation results outputted but model performance unknown.
•	Dice score and plot for training metrics are not provided and unable to evaluate the model performance.
Algorithm implementation: 
•	Algorithm implemented in PyTorch for the UNet3D model and functions.
Design: 
•	Modularised and reusable code.
Commenting: 
•	Some comments throughout the code. 
Difficulty: 
•	3D UNet with residual blocks included for each layer.
•	Model performance unknown.

**Comment by Nicholas-Roughley** [comment]
Completed Feedback request and removed cache files.

**Comment by shakes76** [comment]
Segmentations not one hot encoded -2 additionally, performance unknown and not visualised -1, feedback applied +2

**Comment by shakes76** [comment]
Cant merge because of conflicting changes to main repo files (gitignore). Please update for merge, doesn't affect grade.

**Pull request merged**
