### PR TITLE
HipMRI VQVAE generative model - s4742487

### PR DESCRIPTION
**Pull request by ConyllUQ**
Created a VQVAE generative model for the HipMRI dataset on Prostate Cancer. 
Final SSIM was 0.6044.
Reconstructed images look like faded versions of the original generated images. This means that the reconstructed images are still clear and represent the original images effectively; they purely just have a lighter value on the greyscale.

Files included are:
- dataset.py : Functions to get the data loader for the MRI dataset.
- modules.py : VQVAE module, and subsequently the Encoder, Vector Quantiser, Decoder, Residual Layer and Residual Stack modules.
- train.py : Functions to train VQVAE model.
- predict.py : Functions to evaluate VQVAE model on test data.
- README.md : Information on file use and results.
- readme_images : Graphs and images utilised in README.md file.

Kind regards,
Conyll Forbes (s4742487)

### CODE REVIEW

**Comment by Uto0op** [comment]
Recognition problem: VQVAE on HipMRI ---- Hard Difficulty

1. Algorithm solves the problem: 
Reasonably clear reconstructed images and SSIM over 0.6 (5 Marks)

2. Algorithm demonstrated and functions: (3 Marks)

3. Design:
Modularized and good (1 Mark)

4. Commenting: 
Meaningful docstrings and comments (1 Mark)

5. Algorithm above Normal Difficulty: (5 Marks)

6. Algorithm is Hard difficulty: (5 Marks)

Suggestions:
- Very detailed description of the overall workflow, but you could also justify the hyperparameter tuning process (e.g. why you ended up choosing LR of 1e-4, what else you had attempted and what were their implications);
- No explanation is given to the training/validation metrics (e.g. why the validation SSIM is higher while there's no noticeable overfitting);
- readme_images are not loaded/shown in the README.md due to the wrong path;
- You could also briefly explain why VQVAE generates somewhat blurry images based on its structure/properties.

**Comment by YashMitttal** [comment]
Some additional suggestions:

- Parameter Initialization: Could you explain why you initialized certain parameters with specific values? This helps others understand the reasoning behind your choices and can also support your model’s effectiveness.
- Future Improvements: Please make sure to mention any ideas you have for further improving the model, such as testing different quantization methods or adjusting the architecture. It shows a proactive approach to optimizing your work.
- Evaluation Metrics: Be clear about the evaluation metrics you used and why they’re suitable for this type of task, especially with MRI data. This clarification adds depth to your model’s assessment.

Overall, the algorithm solves the problem well. Also, please check your references.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>Good solution to problem. </td><td></td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. VQVAE (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF submitted.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). Late submission.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-1</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by shakes76** [comment]
Approved extension +2, poor visualisation of results -2

**Pull request merged**
