### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by TopHat-Jestr**
code just prints some text, such that it won't abort.
could not complete the model in time. As such, it can not demonstrate a working Unet model.
I should have aimed for the 2d task to begin with, rather than getting slowed down by the differences needed for the 3d task (my original goal)

### CODE REVIEW

**Comment by celinsze** [comment]
**This is an initial inspection, no action is required at this point**
Recognition problem: total 3 Marks
Problem solving: (0)
•	Model incomplete and no results or plots are provided.
Algorithm implementation: (1.5)
•	Algorithm implemented in PyTorch for the UNet2D model and functions.
•	Functions incomplete
Design: Modularised and reusable codes. (1)
Commenting: Clear comments partially completed. (0.5)

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Adequate design and implementation. </td><td>-1</td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>Header blocks. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Model incomplete.</td><td>-3</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Normal. UNet3D (Normal Difficulty)</td><td>-5</td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Some/Adequate Meaningful commit messages. Minimal.</td><td>-1</td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Acceptable. Results missing. Report incomplete.</td><td>-4</td></tr>
	<tr><td></td><td>Model/technical explanation :Acceptable. </td><td>-1</td></tr>
	<tr><td></td><td>Description and Comments :Acceptable. References missing.</td><td>-1</td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Pull Request has problems: Late submission.</td><td>-2</td></tr>
	<tr><td></td><td>Feedback action required: Feedback marks possible +2 if the requested changes are made. Remove model cache files for merge.</td><td>-2</td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-20</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by gayanku** [comment]
Feedback marks possible +2 if the requested changes are made (see above).

**Comment by hanemma7moud** [comment]
Felipe Menezes

**Comment by hanemma7moud** [comment]
Felipe Menezes

**Comment by shakes76** [comment]
Approved extension +2, model incomplete and doesnt solve problem -2 additionally, no results/plots -2

Cant merge because of conflicting changes to main repo files (model files). Please update for merge, doesn't affect grade.

**Comment by TopHat-Jestr** [comment]
Hi there, I've removed the files that were in \_\_pycache__ which I think should resolve the issues with merging.
Sorry for the trouble, let me know if there's anything else I can do.

**Comment by shakes76** [comment]
Feedback applied +2

**Pull request merged**
