### PR TITLE
Topic recognition - (46979597) Task 5: Vision Transformer (ViT) on the ADNI dataset

### PR DESCRIPTION
**Pull request by Lojlk**
### Project Overview
Author: John Kong (4697959)

This project addresses Task 5, focusing on the classification of Alzheimer’s Disease (AD) vs. Normal Cognition (NC) using a Vision Transformer (ViT) model. The ADNI dataset, consisting of brain MRI images, is employed for this task. For more detailed information about the problem, model architecture, training processes, and results, refer to the README.md file.

### Main Contributions: Files and Folders

`README.md`: Contains comprehensive documentation, including problem description, model architecture, dependencies, training details, results, and references.

`runner-comp.sh`: Script to run training and evaluation on the HPC.

`results/`: Directory with subfolders showcasing selected training outcomes (both good and bad). Each subfolder includes relevant accuracy curves, confusion matrices, loss curves, predictions, and detailed output files.

`Readme-imgs/`: Contains images used in the README.md documentation.

`dataset.py`: Script for data loading, preprocessing, and transformation, handling data leakages.

`modules.py`: Implementation of Vision Transformer components, including the core building blocks like PatchEmbedding and TransformerEncoderBlock.

`train.py`: Script for training the model, including validation and testing steps. This is also where the configurations for hyperparameter tuning are set. 

`predict.py`: Evaluates model performance and visualizes results such as confusion matrices.

### Notes on Final Results

The hyperparameter fine-tuning process involved systematically adjusting various model parameters to improve classification performance. Key modifications included: Learning Rate Adjustments, Batch Size Variations, Dropout Rates, Adjustments to weight decay and Epoch size. 

After hyperparameter fine-tuning, the **best test accuracy achieved was 67.2%**, which is slightly lower than the best validation accuracy of 72%. This discrepancy suggests that the model may still be experiencing overfitting.

### CODE REVIEW

**Comment by prprakash02** [comment]
**This is an initial inspection**

**1) Recognition Problem:**

a) Algorithm solves the respective pattern recognition problem appropriately: **(+3)**
b) Algorithm implemented in PyTorch demonstrated and functions as intended to solve the respective problem: **(+3)**
c) Good design implemented in PyTorch that solves the problem: **(+1)**
d) Commenting: **(+1)**
e) Algorithm is normal or above difficulty while implemented in TF/PyTorch while solving the respective problem: Hard level **(+5)**
f) Algorithm is hard difficulty while implemented in TF/PyTorch while solving the respective problem: Hard level **(+5)**

**(Total: 18/20)**

**2) Commit Log:**

a) Meaningful commit messages with evidence of individual work and originality: **(+2)**
b) Progressive commits and logical log structure providing evidence of individual work and originality: **(+3)**

**(Total: 5/5)**

**3) Documentation:**

Requirement:

Tittle: Done
Description of the algorithm: Done
Problem that it solves: Done
How it works in a paragraph (example any pre-processing): Done
Figure/visualisation (any input, output & results): Done
Dependencies: Done

Marking:

a) Description and explanation of the working principles of the algorithm implemented and the problem it solves: **(+5)**
b) Description of usage and comments throughout scripts: **(+3)**
c) Proper formatting using GitHub markdown: **(+2)**

**(Total: 10/10)**

**4) Pull Request**

a) Creating a pull-request into correct branch with a working and demonstrable version of the algorithm: **(+2)**
b) Incorporating feedback into the pull request: **(+2)**
c) Description of and comments within the pull request: **(+1)**

**(Total: 5/5)**

**Feedback:**

- Good attempt
-  The model could is very powerful, hence it overfits soon. 
- I would suggest looking into a smaller ViT model (maybe some variation) along with some data augmentation
- You could also try some packages that perform smart hyper-param tuning

**Any Changes Needed: No**

**Comment by aniketgupta17** [comment]
Observational Feedback

Pull Request:
Correctly created the Pull request from Topic Recognition Branch .
The pull request includes a clear description about the file structure .
No previous feedback incorporated .

File Organizing: Well-organized files.

Commit Log:
Commit messages are  progressive for the Recognition Problem solved using 4 files .
Commits are regularly made.

Documentation:

Code comments and docstrings are included.
Proper GitHub markdown formatting is used, with organized headings, lists, and code blocks.
Should  add about Conclusion and future improvements in the ReadMe.

**Comment by Lojlk** [comment]
@prprakash02 Thanks for the feedback, I have removed the SLURM job script has required.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>Good solution to problem. </td><td></td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. ViT (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). On time submission.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-1</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by shakes76** [comment]
Well done

**Pull request merged**
