### PR TITLE
s4803414: Prostate 3D Dataset Segmentation with 3D Improved U-Net Architecture

### PR DESCRIPTION
**Pull request by ShwaaGIT**
This pull request introduces an improved 3D U-Net for prostate segmentation. Implemented ResNet blocks for better feature extraction, added data augmentation for improved performance, and adjusted hyperparameters. Achieved an average Dice score of 0.826 on validation, with all classes scoring above 0.7.
___
Files:
* Content/ : Images used in the README file.
* README.md : Provides an overview of the project, instructions on how to run the model, details about the dataset, and a summary of the results.
* modules.py : contains the source code for the model components. Each component is implemented as either a class or a function, providing modular building blocks for constructing the 3D U-Net with ResNet blocks.
* dataset.py : Responsible for loading and preprocessing the data. This script defines a data loader that handles reading the dataset, applying necessary transformations, and batching the data for training and validation.
* predict.py : Demonstrates the usage of the trained model. It prints out the prediction results and provides visualizations, such as segmentation overlays or sample slices with predicted masks, to showcase the model's performance.

### CODE REVIEW

**Comment by celinsze** [comment]
**This is an initial inspection, no action is required at this point**

Recognition problem: 
Problem Solving: 
•	Algorithm solves the problem and achieves a Dice score of above 0.72 for all labels.
•	Missing plot for training metrics.
Algorithm implementation: 
•	Algorithm implemented in PyTorch for the UNet3D model and functions.
Design: Modularised and reusable code.
Commenting: Clear comments throughout the code. 
Difficulty: 
•	3D UNet with residual blocks included for each layer.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>Good solution to problem. </td><td></td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. UNet3D (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Acceptable. Missing plot for training metrics.</td><td>-2</td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). On time submission.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-3</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by hanemma7moud** [comment]
Joshua Beehler

**Comment by shakes76** [comment]
Segmentations not one hot encoded -2 additionally, meaningful commit messages -1

**Pull request merged**
