### PR TITLE
GFNet for ADNI classification - 47147571

### PR DESCRIPTION
**Pull request by chenzhi-liu**
Implementation of ADNI classification (task 5) using GFNet. By using a set of techniques in the training and testing phases, as well as data augmentation methods for training, I have achieved a test accuracy of 80.67% on the test set. More details are included in the `README.md`.

The following files are provided:

- `README.md`: Report about the implementation of models, training, testing, and other details.
- `dataset.py`: The implementation of two custom Dataset classes used to load the ADNI dataset.
- `modules.py`: The GFNet model adapted from the official implementation.
- `train.py`: Train, validate, test, and save the model.
- `predict.py`: Load and test the trained model on the test set.
- `utils.py`: Helper functions for training and testing the model.

Author: Chenzhi Liu  
Student number: 47147571

### CODE REVIEW

**Comment by aniketgupta17** [comment]
Observational Feedback

Pull Request:
Correctly created the Pull request from Topic Recognition Branch .
The pull request includes a clear description about the file structure .


File Organizing: Well-organized files.

Commit Log:
Commit messages are progressive for the Recognition Problem solved using 4 files . 
Commits are regularly made, showing incremental development rather than bulk updates.

Documentation:
The README file can be more descriptive on the achieved results 
Code comments and docstrings  are included.
Proper GitHub markdown formatting is used, with organized headings, lists, and code blocks.
Can add about Conclusion and  future improvements in the ReadMe.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>Header blocks. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>Good solution to problem. </td><td></td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. Uses Data Aug</td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard.  GFNet (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Acceptable. </td><td>-1</td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF Checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). </td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-1</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by shakes76** [comment]
Good work. Meaningful commit messages -1

**Comment by chenzhi-liu** [comment]
> Good work. Meaningful commit messages -1

Thank you for your feedback. I would like to understand why my commit was considered not meaningful, leading to a mark deduction. I compared my commit with those of other students who did not lose marks and believe my commit message is clear and meaningful, as each sentence describes the main progress.

**Pull request merged**
