### PR TITLE
Add Siamese Network Classifier for Melanoma Detection- s46972691

### PR DESCRIPTION
**Pull request by gpot1**
# Pull Request: Add Siamese Network Classifier for Melanoma Detection

This pull request introduces a Siamese Network-based classifier for melanoma detection in skin lesion images, as part of the COMP3710 assignment.

## Summary

- **Implemented**:
  - A Siamese Network to learn embeddings that capture similarities between skin lesion images.
  - An image classifier using the learned embeddings to classify lesions as benign or malignant.

- **Performance**:
  - Achieved a test accuracy of **95.11%**.
  - Obtained an **AUC-ROC** score of **0.8492**.

- **Documentation**:
  - Added a detailed `README.md` with instructions on usage, dependencies, and results.
  - Included example inputs, outputs, and visualizations (ROC curve, confusion matrix).

## Files Added

- `recognition/SiameseClassifier_46972691/`
  - `train.py`
  - `predict.py`
  - `modules.py`
  - `dataset.py`
  - `README.md`
  - Additional files and directories as needed.

## Notes

- All dependencies and usage instructions are provided in the `README.md`.
- The project includes progressive commits demonstrating development stages.
- Implemented data augmentation and class imbalance handling techniques to improve model performance.

### CODE REVIEW

**Comment by hanemma7moud** [comment]
### This is an initial inspection, no action is required at this point
**Recognition Problem** : total : **18**

**Solves problem**: The solution is appropriate for the problem. (**3**)
The resulting manifold is not included to evaluate the discriminitive embeddings.
The classifier performs well in terms of overall accuracy and AUC.
Although the model is highly specific in identifying benign cases (specificity= 96.3), it has a low recall/sensitivity of 28.2%, indicating poor performance in identifying malignant cases.  
 
**Implementation functions as intended** (**3**)

**Good design**: Well-designed (**1**)

**Commenting**: Clear and sufficient comments throughout the code. (**1**)

**Difficulty: Hard** (**10**)

Note:
- As seen in the confusion matrix, sensitivity was relatively low at the default threshold. Adjusting the threshold could help balance sensitivity and specificity better if the priority is identifying malignant cases accurately.
- Further experimentation is needed to achieve balanced performance, particularly to improve the model's ability to classify malignant cases.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>Header blocks. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. </td><td>-2</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting missing. </td><td>-1</td></tr>
	<tr><td></td><td>No Data leakage found. Has data splitting. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard.  Siamese network (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Some/Adequate Meaningful commit messages. </td><td>-1</td></tr>
	<tr><td></td><td>Some/Adequate Progressive commits. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Acceptable. </td><td>-1</td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF Checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). On time.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-6</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by hanemma7moud** [comment]
Harrison Martin

**Comment by shakes76** [comment]
Manifold not included -2

**Pull request merged**
