### PR TITLE
Semi-Supervised Node Classification on Facebook Page-Page Network using Graph Neural Networks

### PR DESCRIPTION
**Pull request by ycKevin**
Overview:

This Pull Request introduces a Graph Neural Network (GNN) model for semi-supervised multi-class node classification using the Facebook Large Page-Page Network dataset. The model uses multi-layer GATConv layers to classify nodes into categories such as government, tvshow, company, and politician.

The submission includes:

- Training and prediction scripts.
- A detailed README file explaining setup, usage, model details and discussions.
- Visualizations demonstrating the performance and interpretability of the model.

File Descriptions
- train.py: Script for training the GNN model on the Facebook dataset.
- predict.py: Script for loading the trained model and predicting node classes.
- modules.py: Defines the GNN architecture with multiple GATConv layers for node classification.
- dataset.py: Handles loading and processing the dataset from the provided .npz file.
- README.md: Detailed project documentation, setup instructions, and usage guide.
- Visualizations:
  - graphs/training_validation_loss.png: Training and validation loss over epochs.
  - graphs/umap_embeddings.png: UMAP visualization of node embeddings.

Key Features
- Model Architecture: Multi-layer GNN using Graph Attention Networks (GAT) for leveraging node relationships and attention mechanisms.
- High Accuracy: The model achieves a 98.24% prediction accuracy on the dataset.
- Visual Interpretability: UMAP embeddings were generated to visualize the learned representations and demonstrate clustering by class.

Model Performance Visualizations
- Training and Validation Loss:
The training and validation loss graph indicates that the model was trained effectively without overfitting, with loss converging to low values.
- UMAP Embeddings Plot:
The UMAP visualization shows distinct clusters representing different node classes, highlighting the model's capability to separate different types of Facebook pages.

Request for Review
- Functionality Verification:
  - Please verify the functionality of train.py and predict.py.
  - Ensure that the model can be successfully trained and tested with the provided dataset.
- Accuracy and Performance:
  - Confirm that the reported 98.24% accuracy is reproducible.
  - Evaluate the quality and clarity of the visualizations included in the graphs folder.
- Documentation:
  - Review the README.md for accuracy, completeness, and clarity.
  - Verify that all instructions (Google Colab or local setup) are detailed enough for easy replication.
- Environment Setup:
  - The code has been tested on Google Colab. Make sure to verify the setup for both Google Colab and a local environment as mentioned in the README.
  - Dependencies include PyTorch, torch_geometric, and umap-learn; please check if they are properly listed and easy to install.

Next Steps:
- Feedback Incorporation:
  - I am open to any suggestions or feedbacks!
  - Any additional insights on the UMAP visualization or hyperparameter tuning would be greatly appreciated!

If the submission meets the functional and documentation standards, please kindly proceed with merging this pull request into the main branch.

Thank you!

Chen Yang
47867637

### CODE REVIEW

**Comment by gayanku** [comment]
**This is an initial inspection, no action is required at this point**
GNN FB Page-Page Network dataset ---- Normal Difficulty
| Category	| | Marks | Comments |	
| :---  | :---: | :---: | :---  |		
| Algorithm solves the problem 		| 5 | 4.5 | Some overfitting seen |
| Implementation functions as intended	| 3 | 3 | 3/4 layer GAT, not GCN, torch_geometric/GATConv. This is OK. |
| Good design 					| 1 | 0.5 | Modular, Reusable if heads was a parameter in GNN class |
| Commenting 					| 1 | 1 | Meaningful docstrings and comments |
| Algorithm above Normal Difficulty 	| 5 | 5 | |
| Algorithm is Hard difficulty 			| 5 | 0 | Normal Difficulty |
| Section IV : Max mark 15 from 20		|   | **14**   | |

**TSNE / UMAP:** 
Good, though would have expected to see a bit more separation at the reported accuracy.
- Discussion: Good.

**Suggestions:**
Hard coded hyper parameters should be avoided (epochs, heads)
Not mentioned  Test accuracy on test split.
Code can have some early stop, ex: train loop should save best model by keeping track of current best accuracy.
Could add a hyper parameter search or discuss how the values were obtained.
GCN code is **not reusable ** as values are hard coded.
Looks like the model might be overfitting as test loss is increasing.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Adequate design and implementation. Avoid hard coded values.</td><td>-1</td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Some overfitting.</td><td>-1</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Normal. GNN Task.</td><td>-5</td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). </td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-8</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by gayanku** [comment]
Feedback marks possible +2 if the requested changes are made (see above).

**Comment by shakes76** [comment]
Commit messages are minimal -1 additionally.

**Pull request merged**
