### PR TITLE
Implement GCN for Node Classification on Facebook Dataset

### PR DESCRIPTION
**Pull request by Hemil107**
**GCN Model for Facebook Dataset**

This pull request implements a Graph Convolutional Network (GCN) for node classification on a Facebook-like social network dataset using PyTorch Geometric. The key components include:

**Data Loading and Preprocessing:**

Load graph data (features, edges, labels) from an .npz file.
Add self-loops to stabilize the graph structure during training.

**Model Architecture:**

A 3-layer GCN model with ReLU activations.
Hidden layer size: 64 units.
Final layer output matches the number of unique classes in the dataset.

**Training and Optimization:**

Uses Adam Optimizer with a learning rate of 0.01 and weight decay of 5e-4.
Trains for 160 epochs, with loss printed every 10 epochs.

**Evaluation and Prediction:**

Evaluates model performance using accuracy score and classification report.
Achieves 96% accuracy on the given dataset.

**Embedding Visualization:**

Utilizes UMAP to visualize learned embeddings and identify node clusters based on class labels.
Files Added:
dataset.py: Handles loading the dataset.
preprocess.py: Adds self-loops and prepares data for training.
modules.py: Defines the GCN architecture.
train.py: Implements the training loop.
predict.py: Handles prediction and evaluation logic.
visualise.py: Generates UMAP visualizations of embeddings.
main.py: Main script to execute the entire workflow.

**Performance Summary:**

Training Loss: Converges to 0.1093 by epoch 150.
Accuracy: 96% across all classes.

Class-wise metrics:  Precision, Recall, and F1-scores for all classes are above 0.96.

### CODE REVIEW

**Comment by gayanku** [comment]
**This is an initial inspection, no action is required at this point**
GNN FB Page-Page Network dataset ---- Normal Difficulty
| Category	| | Marks | Comments |	
| :---  | :---: | :---: | :---  |		
| Algorithm solves the problem 		| 5 | 4.5 | No early stop|
| Implementation functions as intended	| 3 | 3 | 3 layer GCN, torch_geometric/GCNConv |
| Good design 					| 1 | 1 | Modular, Reusable |
| Commenting 					| 1 | 1 | Meaningful docstrings and comments |
| Algorithm above Normal Difficulty 	| 5 | 5 | |
| Algorithm is Hard difficulty 			| 5 | 0 | Normal Difficulty |
| Section IV : Max mark 15 from 20		|   | **14.5**   | |

**TSNE / UMAP:** 
Good, though would have expected to see a bit more separation.
- Discussion: Good, with a bit more depth useful.

**Suggestions:**
Hard coded hyper parameters should be avoided.
Setup/Reproducibility/Requirements would be good to have.
Would be good to see the test/train losses in comparison. 
Code can have some early stop, ex: train loop should save best model by keeping track of current best accuracy.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. No early stop.</td><td>-1</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. No loss / accuracy train/test graphs.</td><td>-1</td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Normal. GNN Task.</td><td>-5</td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Some/Adequate Progressive commits. All 14 commits in 1 day</td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Acceptable. </td><td>-1</td></tr>
	<tr><td></td><td>Description and Comments :Acceptable. References missing.</td><td>-1</td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Pull Request has problems. </td><td>-2</td></tr>
	<tr><td></td><td>Feedback action required: Feedback marks possible +2 if the requested changes are made. Update PR to correct branch. Remove dataset from commit (.npz)</td><td>-2</td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-15</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by gayanku** [comment]
Feedback marks possible +2 if the requested changes are made (see above).

**Comment by shakes76** [comment]
Feedback +2

**Pull request merged**
