### PR TITLE
Topic 8: StyleGAN using PyTorch on ADNI dataset

### PR DESCRIPTION
**Pull request by Ojas0305**
# Pull Request Description

## **Objective**

This pull request creates a StyleGAN model using PyTorch to perform Task 8. The model implements the GAN architecture and incorporates an embedded AdaIN layer that can produce high-quality images for the brain of "Normal Cognition" and "Alzheimer's Disease" from the ADNI dataset. Detailed information about the training process, model architecture, and generated images is available in the README.

### **Selected Task:** 
8. Create a generative model of one of the ADNI brain data set (see Appendix for links) using either a
variant of StyleGAN [10]/StyleGAN2 [11] or Stable Diffusion [12] that has a “reasonably clear image”.
You should also include a TSNE or UMAP embeddings plot with ground truth in colors and provide a
brief interpretation/discussion. See recent UQ work for hints of how to incorporate labels in style. 

The StyleGAN architecture has been implemented using PyTorch. It integrates AdaIN layers, enabling style control in image generation. The generator comprises a sequence of generating blocks with noise injection and AdaIN for enhanced image synthesis. The discriminator is designed to effectively differentiate between original and generated photos, ensuring high-quality results.

### **Efficiency:**
The StyleGAN model generates high-quality realistic brain images showing striking differences between normal cognition and Alzheimer's Disease. Quantitative metrics and visual inspections indicate high fidelity and diversity in the generated images.

## **Dataset Preparation (dataset.py):**

This script describes the `get_dataloader` function, which imports the ADNI dataset and preprocesses it. The transformations involved include resizing, center cropping, conversion to grayscale, tensor conversion, and normalization. This function returns PyTorch DataLoaders to efficiently handle training and evaluation data with batching during model training.

## **Network Modules (modules.py):**

This file defines all the neural network components used within the StyleGAN architecture. Besides the usual custom layers, it includes `PixelNorm`, `AdaIN`, `WSLinear`, `WSConv2d`, `InjectNoise`, `GenBlock`, `MappingNetwork`, `Generator`, `ConvBlock`, and `Discriminator`. Each module is tailored to support the complex functions required by StyleGAN for effective and efficient image generation and classification.

## **Training Script (train.py):**

The `train.py` script implements a function for training the StyleGAN model. It handles data loading, model initialization, training iterations, and checkpointing, as well as visualizing losses. This script utilizes mixed precision training to improve computational efficiency and includes mechanisms to save and load model checkpoints, allowing seamless training continuation and model evaluation.

## **Test Script (predict.py):**

This script generates new synthetic brain images using the trained StyleGAN model. It loads a trained generator, processes input seeds to produce images, and saves them to a specified directory. Additionally, it provides functionality to visualize the generated images for a qualitative assessment of the model's performance.

I would appreciate it if someone could review the changes within this pull request, and if they meet the requirements, please merge. Any constructive feedback on further tweaks or improvements will be gladly welcomed.

Thank you,  
Ojas Ahuja 
47462153

### CODE REVIEW

**Comment by Uto0op** [comment]
Recognition problem: StyleGAN on ADNI ---- Hard Difficulty

1. Algorithm solves the problem: (3 Marks)
Not very clear generated images, it's not reasonable to resize to 64 * 64 as lots of information would be lost -1;
TSNE embedding on the training data without brief interpretation/discussion -1

2. Algorithm demonstrated and functions: (3 Marks)

4. Design: 
Modularized design (1 Mark)

5. Commenting:
Sufficient docstrings and comments (1 Mark)

6. Algorithm above Normal Difficulty: (5 Marks)

7. Algorithm is Hard difficulty: (5 Marks)

**Suggestions**:
- Resizing from 256*256 to 64*64 is not appropriate, causing the generated images being  too small to identify;
- Ideally, according to the reference paper from the task sheet, the embedding should be plotted on the style space. In your `train.py`, you plotted the embedding directly on the training data by using `get_dataloader(FIXED_IMAGE_SIZE, args.batch_size, args.data_root, shuffle=False)` with `args.data_roo` set to the train dir on Rangpur (-0.5). Also, a brief interpretation/discussion is required (-0.5);
- - The losses shown are fine, but the gap suggests it could be further fine-tuned;

**Comment by yexincheng** [comment]
**This is an initial inspection, no action is required at this point**
1. **Solves problem**: Nice documentation and introduction of the network. Reasonable loss for both generator and discriminator. The generated image has low resolution but has reasonable structures. T-SNE does not show clear clusters. The input of T-SNE should be latent space or generated images but used real images.
2. **Implementation**: Data augmentation implemented. Hyperparameters were hard-coded. Clear implementation.
3. **Design**: Good
4. **Comment**: Need more comments for the network class and train function. Good comments for most functions. 
5. **Difficulty**: Hard

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Low image quality.</td><td>-1</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. StyleGAN (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Acceptable. TSNE  interpretation missing.</td><td>-1</td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF Checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Pull Request has problems: Late submission.</td><td>-2</td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-5</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by Ojas0305** [comment]
> Pull Request has problems: Late submission.	-2
Hi, Thanks for the feedback! I just wanted to specify that I had an approved extension at the time of the submission, so not sure why its marked late?

Thank you,
Ojas

**Comment by shakes76** [comment]
Approved extension +2

**Pull request merged**
