### PR TITLE
ViT - 47364417 (ADNI)

### PR DESCRIPTION
**Pull request by praneetdhoolia**
# Overview

This PR introduces a Vision Transformer (ViT) model to classify Alzheimer's Disease using the ADNI brain imaging dataset. The primary goal is to distinguish between normal (NC) and Alzheimer's Disease (AD) cases using the `vit_small_patch16_224` architecture. The model is trained alongside preprocessing and data augmentation techniques to improve generalization.

# Files

The following files are included in this PR:

1. **`dataset.py`**: Loads and preprocesses the ADNI dataset, splitting into training, validation, and test sets.
2. **`modules.py`**: Defines the Vision Transformer model architecture used for classification.
3. **`train.py`**: Contains the training loop, validation steps, and model checkpointing.
4. **`predict.py`**: Evaluates the trained model on the test dataset and outputs performance metrics.
6. **`README.md`**: Provides a project report, including model overview, training process, results, and usage instructions.
7. **`requirements.txt`**: Lists all dependencies required to run the project.
8. **`assets/`**: Contains images and plots used in the `README.md`, such as diagrams and performance graphs.

# Results

The model achieved over **94%** accuracy on the training set and around **85%** on the validation set, indicating effective learning and decent generalization during training. However, the test accuracy dropped to **60-63%**, suggesting overfitting and challenges in generalizing to unseen data.

---

Cheers,

Praneet Dhoolia (47364417)

### CODE REVIEW

**Comment by shaivikaaaa** [comment]
This is an initial inspection

Difficulty : Hard
Task : 5

1) Recognition Problem:

The code looks good, but comments could be better.
The model shows overfitting 

2) Commit Log:

can be much better, most of the commits just have changes related to spacing issues

3) Documentation:

Requirement:

Tittle: Done
Description of the algorithm: Done
Problem that it solves: Done
How it works in a paragraph (example any pre-processing): Done
Figure/visualisation (any input, output & results): Done
Dependencies: Done

4) Pull Request

Looks okay.

Feedback:

Just improve your PR a bit. use markdown in it with an Overview, File structure and a Result section

**Comment by praneetdhoolia** [comment]
Thanks for the feedback! I've formatted my PR accordingly.

**Comment by aniketgupta17** [comment]
Observational Feedback

Pull Request:
Correctly created the Pull request from Topic Recognition Branch .
The pull request includes a clear description about the file structure .
Previous Feedback Incorporated . 

File Organizing: Well-organized files.

Commit Log:
Commit messages are progressive for the Recognition Problem solved using 4 files .
Commits demonstrate logical development flow.

Documentation:
The README file misses on  Dependencies , Reproducibility and Conclusion . 
Code comments and docstrings are included.
Proper GitHub markdown formatting is used, with organized headings, lists, and code blocks.

**Comment by praneetdhoolia** [comment]
Thanks for the observations! I've added the missing sections to the readme.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>No Header blocks. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Model overfitting</td><td>-2</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. ViT (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Some/Adequate Meaningful commit messages. </td><td>-1</td></tr>
	<tr><td></td><td>Some/Adequate Progressive commits. </td><td>-1</td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Pull Request has problems: Late submission.</td><td>-2</td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-7</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by praneetdhoolia** [comment]
Hi, thanks for the feedback! Just a note, I had the same query as one of my peers. I've submitted all of my work under an approved extension, so I would like to appeal the late submission down marking.

Cheers,
Praneet

**Comment by shakes76** [comment]
Approved extension +2

**Comment by shakes76** [comment]
Cant merge because of conflicting changes to main repo files (gitignore). Please update for merge, doesn't affect grade.

**Comment by praneetdhoolia** [comment]
Thanks for grading! I've removed the .gitignore file.

**Pull request merged**
