### PR TITLE
VQVAE2 Generative Model - HipMRI Study - s4803279

### PR DESCRIPTION
**Pull request by farhaan-r**
Name: Farhaan Rashid
Student Number: 48032795

This is my VQVAE2 model for the HipMRI study.

Adding the the following:
dataset.py: handles the creation of tensors from the Nifti files
modules.py: has the necessary components for the VQVAE2 network
train.py: includes the training loop, saving and plotting of the losses during training and validation
predict.py: loads in the trained model and uses the testing set to compare imaged and returns a similarity score
driver.py: you can run this file to execute the training and testing sequentially and the result will be returned
README.md: the documentation of the project
.gitignore: git file to ignore some data types in the commits

I have also included a results folder that has the loss images, the trained model pth file, the original and reconstructed images. It also has the images that are used in the readme file.

### CODE REVIEW

**Comment by Uto0op** [comment]
Recognition problem: VQVAE on HipMRI ---- Hard Difficulty

1. Algorithm solves the problem: (3.5 Marks)
Very clear reconstructed images;
No SSIM output for neither training/validation/test set, only mentioned a number in the README.md -0.5 ;
Unreasonable loss plots without justification -1

2. Algorithm demonstrated and functions: (3 Marks)

4. Design: (1 Mark)
Very modularized design

5. Commenting:
Sufficient docstrings and detailed comments (1 Mark)

6. Algorithm above Normal Difficulty: (5 Marks)

7. Algorithm is Hard difficulty: (5 Marks)

**Suggestions**:

- The description for validation:

> The validation set included 660 images which is about 5.3% of the data. This ensures that were is some data that the model has not seen yet and can be used to strengthen the training of the model. This improves the generalisation of the model and improves the back propogation.
does not make much sense to me;
- Merely mentioned a number of the SSIM is not well-supported;
- No description/justification on the hyperparameters and any tuning on them in Training;
- The loss plot is suspicious, so is the number of epochs. It's hard to expect such good reconstructed images with this loss and LR, it would be good if you can justify;
- Typos and grammer errors in the text.

**Comment by YashMitttal** [comment]
Additional feedback that can be incorporated:

- The Encoder, Vector Quantiser, and Decoder descriptions can be expanded. For example, why is the vector quantizer needed in this model, and how does it improve the generative capabilities?
- The description of the loss function is somewhat vague.
- it would be helpful to describe how the data was used (e.g., preprocessing steps specific to the dataset, any class imbalances or data challenges, etc.).
- There are some typos in the readme, Like Quaniser (in the heading)

Also,l you can expand the content of the pull request. Make it more descriptive.

**Comment by farhaan-r** [comment]
Updated pull request:

This pull request introduces the implementation of the VQVAE2 model for generating synthetic medical images as part of the HipMRI study. The goal of this project is to leverage the VQVAE2 architecture to learn from historical medical imaging data, specifically MRI scans of the hip, and generate new images for educational purposes and further analysis.

The following files have been added to the repository to enable and support this model:

dataset.py: 
this file handles the loading of MRI images in NIfTI format and converts them into PyTorch tensors. It also ensures that the tensors conform to the correct dimensions (i.e., [batch, channels, height, width]) required for the VQVAE2 model. This script facilitates efficient data handling and preprocessing during training.

modules.py: 
this file contains the core components of the VQVAE2 network, including the Encoder, Vector Quantiser, and Decoder. The Encoder reduces the dimensionality of the input image, the Vector Quantiser discretises the latent representations, and the Decoder reconstructs the image from the quantised latent codes. These components work together to learn a compressed representation of the input images and generate high-quality synthetic images.

train.py: 
the training loop is defined in this file. It manages the training process, including: 
Defining and initialising the VQVAE2 model.
Handling the training and validation loss calculations.
Saving the model checkpoint at specified intervals.
Plotting the loss curves for both training and validation, helping to monitor the learning progress.

predict.py: 
this script loads the trained model and uses the test dataset to compare original and generated images. It also calculates the Structural Similarity Index Measure (SSIM) to assess the perceptual quality of the generated images, allowing us to quantify how well the model reconstructs the original data.

driver.py: 
this script serves as the main entry point for the project. By running this file, you can execute the entire training and testing process sequentially, from data loading and training to model evaluation. It is designed to be user-friendly, providing a simple way to run the full pipeline.

README.md: 
the documentation file provides a detailed description of the project, including:
The purpose of the VQVAE2 model for medical image generation.
An overview of the files in the repository.
Instructions on how to set up and run the model.
Expected outputs and results.

.gitignore: 
this file specifies which files and directories should be ignored by Git when committing to the repository. It ensures that unnecessary files, such as large datasets and temporary files, do not get pushed to the remote repository.

Additional Resources:

Results Folder:
The results folder contains important outputs from the model, including:
Loss curves for both training and validation.
The trained model file (.pth format), which contains the learned weights of the VQVAE2 network.
Original and reconstructed images to visually inspect how well the model performs in generating synthetic images.
Images used in the README file for illustration.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>Header blocks. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Some model inconsistancies.</td><td>-2</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. VQVAE (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Acceptable. Unreasonable loss plots without justification. Some vague discriptions. Typos</td><td>-2</td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF submitted.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). On time submission.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-4</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Pull request merged**
