### PR TITLE
Multi-Layer GNN Model for Node Classification and Embedding Visualization

### PR DESCRIPTION
**Pull request by MichaelTu122**
## Description
This pull request contains the final implementation of the **Mixed Graph Neural Network (GNN)** algorithm for **semi-supervised node classification** using the **Facebook Large Page-Page Network Dataset**. The goal is to predict the class of nodes (Facebook pages) based on their features and connections, combining layers of **GCN**, **GAT**, and **GraphSAGE**.

### Key Features:
1. **Algorithm Implementation**:
-  Implemented using a **Mixed GNN model**, combining **GCNConv**, **GATConv**, and **GraphSAGEConv** layers.
-  Trained on node feature vectors (128-dimensions) and graph structure (edges).
-  Uses the **AdamW** optimizer with a learning rate of 0.001 and weight decay of 0.0001.
-  Implements **early stopping** and a **learning rate scheduler** to optimize model performance.

2. **Dataset Loader (dataset.py)**:
  - Loads the Facebook Large Page-Page Network Dataset from a .npz file.
  - Provides edges, features, and target labels in a format that can be used by the Mixed GNN model for training and evaluation.
  - The loaded data is then used by the training and prediction scripts.

3. **Training Script (`train.py`)**:
-  Trains the GNN model using a semi-supervised learning approach.
-  Saves the trained model to `gnn_model.pth`.

4. **Prediction and Evaluation (`predict.py`)**:
-  Loads the trained model and evaluates it on a separate test set.
-  Provides an accuracy score and visualizes the node embeddings using **t-SNE**.
-  t-SNE visualization is saved as an image file in the project directory (images/SNE visualization.png).

5. **README.md**:
-  Provides detailed instructions on setting up the environment, training the model, and making predictions.
-  Describes the structure of the dataset and the overall workflow of the project.

### Final Version of the Algorithm:
- The current version of the algorithm achieves an accuracy of **59.97%** on the test set using the Mixed GNN model (with randomstate=42)
- The t-SNE visualization showcases the learned node embeddings, showing how well the model separates nodes of different classes, although some overlap remains due to model limitations and data complexity.

## Files Modified:
- `dataset.py`: Loads the dataset from .npz format.
- `train.py`: Training script for the Mixed GNN model.
- `predict.py`: Script to evaluate the model and generate visualizations.
- `README.md`: Complete instructions for running the project.
- `modules.py`: Contains the Mixed GNN model implementation (GCN, GAT, GraphSAGE layers).
- `.gitignore`: Updated to ignore unnecessary files (e.g., model checkpoints).

## How to Test:
1. Set up the environment as per the instructions in the `README.md`.
2. Run the training script using `python train.py` to train the model.
3. Use `python predict.py` to evaluate the model and generate the t-SNE plot.

## Known Limitations:
- The model struggles with perfect separation of classes, as seen in the t-SNE visualizations.
- Further hyperparameter tuning or even a more complicated model could potentially improve results.

## Submit by
Tsung-Tse Tu
s4780187

Please review the codes and provide feedback, thank you so much.

### CODE REVIEW

**Comment by gayanku** [comment]
**This is an initial inspection, no action is required at this point**
GNN FB Page-Page Network dataset ---- Normal Difficulty
| Category	| | Marks | Comments |	
| :---  | :---: | :---: | :---  |		
| Algorithm solves the problem 		| 5 | 2.5 |  The use of GCN/GAT in a mixed mode is ok if its justified and works with the dataset, but in this case, achieved accuracy of 60% suggest otherwise. |
| Implementation functions as intended	| 3 | 1.5 | implements a muti type(GCNConv, GATConv, SAGEConv) GCN which might not be ideal for the given dataset |
| Good design 					| 1 | 1 | Modular, Reusable |
| Commenting 					| 1 | 1 | Meaningful docstrings and comments |
| Algorithm above Normal Difficulty 	| 5 | 5 | |
| Algorithm is Hard difficulty 			| 5 | 0 | Normal Difficulty |
| Section IV : Max mark 15 from 20		|   | **11**   | |

**TSNE / UMAP:** 
Class discrimination not present. This is normal as the training accuracy is low. 
Needs more generalization for semantic separation, perhaps some dropouts between GCN layers could help. 
- Discussion: Good, with a bit more depth useful.

**Suggestions:**
Not mentioned if its Test or Train accuracy.
Could add a hyper parameter search or discuss how the values were obtained.
Not GCN based, though it **a** component.
You do not need to do clone() in train loop.

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Adequate design and implementation. </td><td>-1</td></tr>
	<tr><td></td><td>No Spacing and comments. </td><td>-1</td></tr>
	<tr><td></td><td>Header blocks. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Accuracy too low.</td><td>-3</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure present. </td><td></td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Easy. </td><td>-10</td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). </td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-15</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_"

**Comment by MichaelTu122** [comment]
> ## Marking
> Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)
> Adequate design and implementation.	-1
> No Spacing and comments.	-1
> Header blocks.	
> Recognition Problem
> OK solution to problem. Accuracy too low.	-3
> Driver Script present.	
> File structure present.	
> Good Usage & Demo & Visualisation & Data usage.	
> Module present.	
> Commenting present.	
> No Data leakage found.	
> Difficulty : Easy.	-10
> Commit Log
> Good Meaningful commit messages.	
> Good Progressive commits.	
> Documentation
> Readme :Good.	
> Model/technical explanation :Good.	
> Description and Comments :Good.	
> Markdown used and PDF submitted.	
> Pull Request
> Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch).	
> No Feedback required.	
> Request Description is good.	
> TOTAL	-15
> Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness. _Subject to approval from Shakes_

Sorry, but for the difficulty didn't I choose the normal one as shown in the initial comment?

**Comment by gayanku** [comment]
@MichaelTu122 sorry for the shock. I'm still working on the marking tool. Fixed now.

**Pull request merged**
