### PR TITLE
StyleGAN2-ADNI Dataset with t-SNE embeddings -s4854870

### PR DESCRIPTION
**Pull request by bkmund**
Hi Shakes,

Please find attached my PR to solve the problem of generating images and mapping them in the latent space using StyleGAN2. The primary focus is on generating high-resolution medical images, specifically MRI scans from the ADNI dataset, and visualize the style codes in latent space using t-SNE. 
The PR includes training and image generation scripts (train.py, predict.py), as well as t-SNE visualization of the discriminator's feature space (manifold.py). Key components like the generator, discriminator, and mapping network are implemented in modules.py. A dataset.py file is included to load the dataset. Additionally, environment.yml is included as well to faithfully recreate the conda enviroment used  for training.
Dependencies, setup instructions, and further details are documented in the README.md file.

Thank you!

Kind regards,
Baibhav Mund
48548700

### CODE REVIEW

**Comment by Uto0op** [comment]
Recognition problem: StyleGAN on ADNI ---- Hard Difficulty

1. Algorithm solves the problem: (5 Marks)
Somewhat reasonably clear generated images

2. Algorithm demonstrated and functions: (3 Marks)

4. Design: (1 Mark)
Modularized design

5. Commenting:
Sufficient docstrings and comments (1 Mark)

6. Algorithm above Normal Difficulty: (5 Marks)

7. Algorithm is Hard difficulty: (5 Marks)

**Suggestions**:
- The intention of this StyleGAN task is to train one model on two classes of ADNI, and plot the embedding on the style space to see how two classes clustered/represented in the latent space. I just want to point it out but I'm not taking marks off for having two models for two classes;
- You could use the test split for training to improve the performance, since there's no test for this task;
- Some uploaded scripts are not needed.

**Comment by yexincheng** [comment]
**This is an initial inspection, no action is required at this point**
1. **Solves problem**: Nice documentation. Good introduction of the network and code usage. Somewhat reasonable generated images. Reasonable losses. Clear clusters of T-SNE embedding.
2. **Implementation**: Nice usage of ArgParse. Some hypermeters were hard-coded. Could have a function for the training loop. Overall nice and well structured.
3. **Design**: Good
4. **Comment**: Very nice and detailed
5. **Difficulty**: Hard

**Comment by gayanku** [comment]
## Marking
<table><tbody>
  <tr><td colspan='3'><b>Good/OK/Fair Practice (Design/Commenting, TF/Torch Usage)</b></td> </tr>
	<tr><td></td><td>Good design and implementation. </td><td></td></tr>
	<tr><td></td><td>Spacing and comments. </td><td></td></tr>
	<tr><td></td><td>Header blocks. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Recognition Problem</b></td></tr>
	<tr><td></td><td>OK solution to problem. Use of 2 separate models. (No mark deductions). Images quality low.</td><td>-1</td></tr>
	<tr><td></td><td>Driver Script present. </td><td></td></tr>
	<tr><td></td><td>File structure NOT present. Redundant code in repo.</td><td>-1</td></tr>
	<tr><td></td><td>Good Usage & Demo & Visualisation & Data usage. </td><td></td></tr>
	<tr><td></td><td>Module present. </td><td></td></tr>
	<tr><td></td><td>Commenting present. </td><td></td></tr>
	<tr><td></td><td>No Data leakage found. </td><td></td></tr>
	<tr><td></td><td>Difficulty : Hard. StyleGAN (Hard Difficulty)</td><td></td></tr>
	
  <tr><td colspan='3'><b>Commit Log</b></td></tr>
	<tr><td></td><td>Good Meaningful commit messages. </td><td></td></tr>
	<tr><td></td><td>Good Progressive commits. </td><td></td></tr>
	
  <tr><td colspan='3'><b>Documentation</b></td></tr>
	<tr><td></td><td>Readme :Good. </td><td></td></tr>
	<tr><td></td><td>Model/technical explanation :Good. </td><td></td></tr>
	<tr><td></td><td>Description and Comments :Good. </td><td></td></tr>
	<tr><td></td><td>Markdown used and PDF submitted. PDF Checked.</td><td></td></tr>
	
  <tr><td colspan='3'><b>Pull Request</b></td></tr>
	<tr><td></td><td>Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch). ON time.</td><td></td></tr>
	<tr><td></td><td>No Feedback required. </td><td></td></tr>
	<tr><td></td><td>Request Description is good. </td><td></td></tr>
  <tr><td colspan='2'><b>TOTAL</b></td><td>-2</td></tr>
</tbody></table>

Marked as per the due date and changes after which aren't necessarily allowed to contribute to grade for fairness.
_Subject to approval from Shakes_

**Comment by shakes76** [comment]
Needed more training, quality of output low -2

**Pull request merged**
